
.SUFFIXES: .o .cpp
.cpp.o:
	$(CC) -c $(INCLUDE) $(CFLAGS) $<


# Macros

BINDIR = ../bin
CC = g++
CFLAGS = -g -O2 -Wall -static
HEADER = gzstream.h core.h genomic_intervals.h
OBJ = gzstream.o core.o genomic_intervals.o
LIB = -lm -lz -lgslcblas -lgsl 


# Explicit rules

gtools: genomic_regions genomic_overlaps genomic_scans genomic_apps vectors matrix permutation_test

clean:
	rm -f *.o

genomic_regions: $(HEADER) $(OBJ) 
	$(CC) $(CFLAGS) $(INCLUDE) -o $(BINDIR)/genomic_regions genomic_regions.cpp $(OBJ) $(LIB)
genomic_overlaps: $(HEADER) $(OBJ) 
	$(CC) $(CFLAGS) $(INCLUDE) -o $(BINDIR)/genomic_overlaps genomic_overlaps.cpp $(OBJ) $(LIB)
genomic_scans: $(HEADER) $(OBJ)
	$(CC) $(CFLAGS) $(INCLUDE) -o $(BINDIR)/genomic_scans genomic_scans.cpp $(OBJ) $(LIB)
genomic_apps: $(HEADER) $(OBJ)
	$(CC) $(CFLAGS) $(INCLUDE) -o $(BINDIR)/genomic_apps genomic_apps.cpp $(OBJ) $(LIB)
vectors: gzstream.h core.h gzstream.o core.o
	$(CC) $(CFLAGS) $(INCLUDE) -o $(BINDIR)/vectors vectors.cpp gzstream.o core.o $(LIB)
matrix: gzstream.h core.h gzstream.o core.o
	$(CC) $(CFLAGS) $(INCLUDE) -o $(BINDIR)/matrix matrix.cpp gzstream.o core.o $(LIB)
permutation_test: gzstream.h core.h gzstream.o core.o
	$(CC) $(CFLAGS) $(INCLUDE) -o $(BINDIR)/permutation_test gzstream.o core.o permutation_test.cpp $(LIB)



# Implicit rules
gzstream.o: gzstream.h gzstream.c
core.o: core.h core.cpp
genomic_intervals.o: gzstream.h gzstream.o core.h core.cpp genomic_intervals.h genomic_intervals.cpp


